apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ticket-service

  template:
    metadata:
      labels:
        app: ticket-service

    spec:
      containers:
        - name: ticket-service
          image: ticket-service
          imagePullPolicy: Never

          ports:
            - containerPort: 3000

          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

            - name: MONGO_URL
              value: "mongodb://ticket-mongo-service:27017/ticket"

---
apiVersion: v1
kind: Service
metadata:
  name: ticket-service

spec:
  selector:
    app: ticket-service

  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000

  type: ClusterIP
